export default [
  {
    id: 1,
    name: 'Baru',
    description: 'Permintaan survey sedang diajukan.',
    status: 'Penawaran Baru',
    color: '#2E3192',
    bg: '#EBF0FF',
    kategori: 'active',
  },
  {
    id: 1,
    name: 'Baru',
    description: 'Sample komoditi telah diterima.',
    status: 'Sample Diterima',
    color: '#149614',
    bg: '#EBFFEB',
    kategori: 'active',
  },
  {
    id: 1,
    name: 'Baru',
    description: 'Sample komoditi telah dikirim.',
    status: 'Sample Dikirim',
    color: '#2E3192',
    bg: '#EBF0FF',
    kategori: 'active',
  },
  {
    id: 1,
    name: 'Baru',
    description: 'Permintaan Sample komoditi oleh Talasi.',
    status: 'Request Sample',
    color: '#2E3192',
    bg: '#EBF0FF',
    kategori: 'active',
  },
  {
    id: 1,
    name: 'Baru',
    description: 'Permintaan survey sedang diajukan.',
    status: 'Baru',
    color: '#2E3192',
    bg: '#EBF0FF',
    kategori: 'active',
  },
  {
    id: 2,
    name: 'Survey',
    description: 'Tunggu kedatangan surveyor.',
    status: 'Survey',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 3,
    name: 'Verifikasi',
    description: 'Survey sedang dalam verifikasi.',
    status: 'Verifikasi',
    // color: '#A233FF',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 4,
    name: 'Persetujuan',
    description: 'Konfirmasi harga dari Talasi.',
    status: 'Persetujuan',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 5,
    name: 'Dibatalkan',
    description: 'Sample Ditolak, Anda bisa mengajukan ulang penawaran.',
    status: 'Sample Ditolak',
    color: '#D80909',
    bg: '#FFEBEB',
    kategori: 'finish',
  },
  {
    id: 5,
    name: 'Dibatalkan',
    description: 'Anda bisa mengajukan ulang penawaran.',
    status: 'Batal',
    color: '#D80909',
    bg: '#FFEBEB',
    kategori: 'finish',
  },
  {
    id: 6,
    name: 'Disetujui',
    description: 'Tunggu PO selesai diproses.',
    status: 'Disetujui',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 7,
    name: 'PR Selesai',
    description: 'Siapkan barang.',
    status: 'PO Selesai',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 7,
    name: 'PR Selesai',
    description: 'Siapkan barang.',
    status: 'PR Selesai',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 8,
    name: 'Persiapan',
    description: 'Siapkan barang dan atur pengiriman.',
    status: 'Persiapan',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 9,
    name: 'Pengiriman',
    description: 'Tunggu barang diterima oleh Talasi.',
    status: 'Pengiriman',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 10,
    name: 'Diterima',
    status: 'Diterima',
    description: 'Barang sedang proses penerimaan.',
    color: '#149614',
    bg: '#EBFFEB',
    kategori: 'active',
  },
  {
    id: 10,
    name: 'Penerimaan',
    status: 'Penerimaan',
    description: 'Barang sedang proses penerimaan.',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 10,
    name: 'Selesai Terima',
    description: 'Barang telah diterima, tunggu invoice selesai diproses.',
    status: 'Selesai Terima',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 11,
    name: 'Siap Bayar',
    description: 'Tunggu pembayaran dari Talasi.',
    status: 'Siap Bayar',
    color: '#FF9100',
    bg: '#FFF6EB',
    kategori: 'active',
  },
  {
    id: 12,
    name: 'Selesai',
    description: 'Pembayaran telah selesai.',
    status: 'Selesai',
    color: '#149614',
    bg: '#EBFFEB',
    kategori: 'finish',
  },
  {
    id: 13,
    name: 'Draft',
    description: 'Penawaran ada dalam keranjang.',
    status: 'Draft',
    color: '#93959E',
    bg: '#F5F6F7',
    kategori: 'draft',
  },
];
