import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  topWrapper: {
    height: 230,
    paddingHorizontal: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  profileImage: {
    display: 'flex',
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginRight: 0,
    marginBottom: 12,
  },
  bottomWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 16,
    infoTransaction: {
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      position: 'absolute',
      top: -50,
      width: '100%',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoTransactionLeft: {
      display: 'flex',
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoTransactionRight: {
      display: 'flex',
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderLeftWidth: 1,
    },
    menu: {
      display: 'flex',
      width: '100%',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 8,
      paddingVertical: 14,
      paddingHorizontal: 12,
      marginBottom: 8,
    },
    menuLeft: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
    },
  },
  btnLogout: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    display: 'flex',
    flexDirection: 'row',
    marginVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  version: {
    marginTop: 18,
    fontSize: 12,
    color: '#687083',
    textAlign: 'center',
  },
});

export default styles;
