//action global
export const SET_LOADING = 'SET_LOADING';
export const SET_ISLOGIN = 'SET_ISLOGIN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_TYPE = 'SET_MESSAGE_TYPE';
export const SET_SHOW_ALERT = 'SET_SHOW_ALERT';
export const SET_ALERT_TYPE = 'SET_ALERT_TYPE';
export const SET_MASTER_BANK = 'SET_MASTER_BANK';
export const SET_BANK_LIST = 'SET_BANK_LIST';
export const SET_BANK_PRIMARY = 'SET_BANK_PRIMARY';
export const SET_PHONE_LIST = 'SET_PHONE_LIST';
export const SET_EMPTY_BANK = 'SET_EMPTY_BANK';
export const SET_EMPTY_ADDRESS = 'SET_EMPTY_ADDRESS';
export const SET_VERIFIED = 'SET_VERIFIED';
export const SET_NO_PENAWARAN = 'SET_NO_PENAWARAN';
export const SET_WAREHOUSE_LIST = 'SET_WAREHOUSE_LIST';
export const ADD_QUEUE = 'ADD_QUEUE';
export const DELETE_QUEUE = 'DELETE_QUEUE';
export const SWITCH_THEME = 'SWITCH_THEME';
export const SET_BIOMETRIK_STATUS = 'SET_BIOMETRIK_STATUS';
export const SET_BIOMETRIK_LOADING = 'SET_BIOMETRIK_LOADING';
export const SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY';
export const SET_LIST_CHAT = '  SET_LIST_CHAT';
export const SET_IS_SOCKET_CONNECTED = '  SET_IS_SOCKET_CONNECTED';
export const SET_SELECTED_KUPON = '  SET_SELECTED_KUPON';

export const SET_ALL_LIST_TRANSACTION = 'SET_ALL_LIST_TRANSACTION';
export const SET_LASTEST_TRANSACTION = 'SET_LASTEST_TRANSACTION';
export const SET_LIST_DATA_KOMODITI = 'SET_LIST_DATA_KOMODITI';
export const SET_LASTEST_KOMODITI = 'SET_LASTEST_KOMODITI';
export const SET_LIST_TRANSACTION_ACTIVE = 'SET_LIST_TRANSACTION_ACTIVE';
export const SET_LIST_TRANSACTION_FINISH = 'SET_LIST_TRANSACTION_FINISH';

export const SET_LIST_NOTIFICATIONS = 'SET_LIST_NOTIFICATIONS';
export const SET_ON_UPDATE_IMAGE = 'SET_ON_UPDATE_IMAGE';

//action inspection
export const SET_LIST_UNIT = 'SET_LIST_UNIT';
export const SET_LIST_HISTORY = 'SET_LIST_HISTORY';
export const SET_CURRENT_INSPECTION = 'SET_CURRENT_INSPECTION';
export const SET_LIST_CATEGORY = 'SET_LIST_CATEGORY';
export const SET_LIST_COMMENT = 'SET_LIST_COMMENT';
export const SET_DETAIL_CATEGORY = 'SET_DETAIL_CATEGORY';
export const SET_RESULT_CATEGORY = 'SET_RESULT_CATEGORY';
export const SET_FOTO_UNIT = 'SET_FOTO_UNIT';
export const SET_UPLOAD_FOTO_UNIT = 'SET_UPLOAD_FOTO_UNIT';
export const SET_ADD_UNIT_FORM = 'SET_ADD_UNIT_FORM';
export const SET_ALL_ADD_UNIT_FORM = 'SET_ALL_ADD_UNIT_FORM';
export const SET_DEFAULT_ADD_UNIT_FORM = 'SET_DEFAULT_ADD_UNIT_FORM';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_DEFAULT_DOCUMENT = 'SET_DEFAULT_DOCUMENT';
export const SET_ALL_DOCUMENT_FORM = 'SET_ALL_DOCUMENT_FORM';
export const SET_INSPECTION_REVIEW_NOTE = 'SET_INSPECTION_REVIEW_NOTE';

// action home
export const SET_PAGE = 'SET_PAGE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SET_INPUT = 'SET_INPUT';
export const SET_LIST_DATA = 'SET_LIST_DATA';
export const SET_SELECTED_STATUS = 'SET_SELECTED_STATUS';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';

//action location
export const SET_PICKED_ADDRESS = 'SET_PICKED_ADDRESS';

//action call

export const SET_RTC_TOKEN = 'SET_RTC_TOKEN';
export const SET_CALL_STATUS = 'SET_CALL_STATUS';
export const SET_LABEL_STATUS = 'SET_LABEL_STATUS';
export const SET_AGORA_OPTIONS = 'SET_AGORA_OPTIONS';
export const SET_AGORA_CHANNEL_PARAMS = 'SET_AGORA_CHANNEL_PARAMS';
export const SET_CALL_FROM_ID = 'SET_CALL_FROM_ID';
export const SET_CALL_TO_ID = 'SET_CALL_TO_ID';
export const SET_THERE_IS_INCOMING_CALL = 'SET_THERE_IS_INCOMING_CALL';
export const SET_SHOW_END_CALL_BTN = 'SET_SHOW_END_CALL_BTN';
export const SET_CHANNEL_NAME = 'SET_CHANNEL_NAME';
export const SET_CALL_FROM_NAME = 'SET_CALL_FROM_NAME';
export const SET_FROM_USER_PHOTO = 'SET_FROM_USER_PHOTO';
export const SET_CALL_DATA = 'SET_CALL_DATA';
