import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    paddingHorizontal: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 129,
    height: 48,
  },
  wrapper: {
    padding: 15,
  },
  alert: {position: 'relative', bottom: 60},
  card: {
    display: 'flex',
    padding: 16,
    borderWidth: 1,
    borderColor: '#E3E3E5',
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: 'white',
  },
  cardNoBorder: {
    display: 'flex',
    padding: 16,
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: 'white',
    textAlign: 'center'
  },
  cardSpace: {
    borderRadius: 0,
    marginBottom: 10,
  },
  cardHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomColor: '#E3E3E5',
    borderBottomWidth: 1,
  },
  cardFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopColor: '#E3E3E5',
    borderTopWidth: 1,
  },
  borderStatus: {
    margin: 10,
    marginLeft: 0,
    paddingLeft: 8,
    borderLeftWidth: 4,
  },
  boxIcon: {
    backgroundColor: '#F5F6F7',
    borderRadius: 50,
    width: 48,
    height: 48,
  },
  image: {
    width: 60,
    height: 60,
  },
  item: {
    display: 'flex',
    flexDirection: 'row',
    marginHorizontal: 5,
    marginRight: 10,
  },

  // Detail
  cardKomoditi: {
    display: 'flex',
    paddingBottom: 12,
    borderColor: '#E3E3E5',
    borderWidth: 1,
    marginVertical: 6,
    marginTop: 15,
    borderRadius: 8,
    position: 'relative',
  },
  sku: {
    padding: 5,
    height: 65,
    justifyContent: 'space-between',
    flexShrink: 1,
    // backgroundColor: 'red',
  },
  detailSku: {
    marginHorizontal: 10,
    // marginTop: 0,
    paddingBottom: 10,
    lineHeight: 30,
  },
  dashed: {
    borderBottomWidth: 1,
    borderBottomColor: '#797B8A',
    borderStyle: 'dashed',
    marginVertical: 10,
  },
  discount: {
    backgroundColor: '#FFEBEB',
    padding: 5,
    borderRadius: 5,
    width: 130,
  },
  koreksi: {
    backgroundColor: '#EBF0FF',
    padding: 5,
    borderRadius: 5,
    width: 130,
  },
  coupon: {
    backgroundColor: '#FFF6EB',
    padding: 5,
    borderRadius: 5,
    width: 130,
  },
  couponRound: {
    backgroundColor: '#FFF6EB',
    padding: 8,
    borderRadius: 50,
    marginRight: 5,
  },
  cardRiwayat: {
    display: 'flex',
    padding: 10,
    margin: 10,
    backgroundColor: '#F5F6F7',
  },
  riwayatDetail: {
    display: 'flex',
    backgroundColor: 'white',
    padding: 10,
    marginVertical: 10,
  },
  riwayatHarga: {
    display: 'flex',

    paddingVertical: 5,
    borderRadius: 4,
    width: '50%',
    alignItems: 'center',
  },
  infoPengiriman: {
    backgroundColor: '#EBF0FF',
    padding: 8,
    marginVertical: 12,
    borderRadius: 5,
  },
  bankCard: {
    marginVertical: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E3E3E5',
    borderRadius: 8,
  },
  btnCancel: {
    backgroundColor: '#F5F6F7',
    marginVertical: 10,
    padding: 12,
    alignItems: 'center',
  },
  badgeVoucher: {
    flexDirection: 'row',
    backgroundColor: '#FF9100',
    justifyContent: 'space-around',
    width: 115,
    padding: 4,
    // paddingHorizontal: 8,
    borderRadius: 4,
    borderBottomRightRadius: 0,
    position: 'absolute',
    right: -10,
    top: -10,
  },
  triangleCorner: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderRightWidth: 10,
    borderTopWidth: 10,
    borderRightColor: 'transparent',
    borderTopColor: '#B86800',
    position: 'absolute',
    right: 0,
    top: 24,
  },
  profileImage: {
    display: 'flex',
    width: 50,
    height: 50,
    borderRadius: 50,
    // borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progres: {
    position: 'relative',
    marginLeft: 3,
    paddingLeft: 9,
  },
  progresDetail: {
    borderLeftWidth: 1,
    paddingBottom: 8,
    paddingLeft: 15,
  },
  dot: {
    width: 18,
    height: 18,
    borderRadius: 50,
    position: 'absolute',
  },
  activeDot: {
    backgroundColor: '#2E3192',
  },
  inactiveDot: {
    backgroundColor: '#E3E3E5',
  },
  headerFixed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: 5,
  },
  button: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    width: '100%',
    padding: 10,
    marginVertical: 8,
    zIndex: 1,
    backgroundColor: '#fff',
    borderColor: '#CBCCD1',
    borderWidth: 1,
    borderRadius: 4,
  },
  buttonText: {
    flex: 1,
  },
  iconDropown: {
    position: 'absolute',
    right: 10,
  },
  dropdown: {
    position: 'absolute',
    backgroundColor: '#fff',
    width: 'auto',
    top: 50,
    height: 'auto',
    borderColor: '#CBCCD1',
    borderWidth: 1,
    borderRadius: 4,
    // zIndex: 3,
    // elevation: 3,
  },
  dropdownText: {
    padding: 10,
    margin: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#CBCCD1',
  },
});

export default styles;
